---
title: 'Tidy Tuesday #2'
author: "Jenny Li"
output: 
  html_document:
    df_print: paged
    code_download: true
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```


```{r libraries}
library(tidyverse)     # for graphing and data cleaning
library(lubridate)     # for date manipulation
library(ggthemes)      # for even more plotting themes
library(janitor)       # for cleaning variable names
theme_set(theme_minimal()) # My favorite ggplot() theme :)
```

### Chart type
Bar graph

### Type of data
NA

### Reason for including the chart
DuBoisChallenge

### Link to data or source
[github repository page](https://github.com/ajstarks/dubois-data-portraits/tree/master/challenge/2022)

## Data choice 2: 

```{r}
# Read in the data for the week
# Data for Challenge 1:
tam_aircraft <- readr::read_csv('https://raw.githubusercontent.com/ajstarks/dubois-data-portraits/master/challenge/2022/challenge10/data.csv')
```
```{r}
tam_aircraft %>%
  mutate(`Percent Not Enrolled` = 100 - `Percent Enrolled`) %>%
  pivot_longer(cols = -Year,
               names_to = "Enrolled",
               values_to = "Percent") %>%
  mutate(label_y = Percent) %>% 
  ggplot(aes(x = Year, y = Percent) )+
  geom_col(aes( fill = Enrolled)) +
  scale_x_continuous(position="top")+
  labs(title = "PROPORTION OF TOTAL NEGRO CHILDREN OF SCHOOL AGE WHO ARE ENROLLED IN THE PUBLIC SCHOOLS",
       x = NULL,
       y = NULL,
       fill=NULL) +
  scale_fill_manual(
    values = c("firebrick3", "black"),
    labels = c("PROPORTION OF CHILDREN ENROLLED", "PROPORTION OF CHILDREN NOT ENROLLED")
  ) +
  geom_text(aes( y = label_y, label = Percent), vjust = +2.1, colour = "black")+
 theme_minimal(base_size = 11) +
  theme(
    plot.title = element_text(hjust = 0.1, face = "bold", size = 8),
    axis.text.x = element_text(
      face = "bold",
      hjust = 2,
      vjust = 2
    )
  )
```


